name: tests

on:
  push:
    branches: [main, test-me-*]
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 15

    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          python: 3.9
          toxenv: py39
        - os: ubuntu-latest
          python: '3.10'
          toxenv: py310
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Get pip cache dir
        id: pip-cache-dir
        run: echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

      - name: Use pip cache
        id: pip-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ matrix.os }}-pip-${{ matrix.python }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ matrix.os }}-pip-${{ matrix.python }}-

      - name: Install Packages
        run: python -mpip install --upgrade pip tox

      - name: Run Tox
        run: tox -e ${{ matrix.toxenv }}
